config/routes.rb
WatchTower::Application.routes.draw do
  
  get "tweets/index"

  resources :streams

  root :to => 'tweets#index'

end

app/models/stream.rb
class Stream < ActiveRecord::Base
  validates :hashtag, presence: true
end

app/models/tweet.rb
class Tweet
  def self.from_streams
    tweets = []
    streams = Stream.all
    
    streams.each do |stream|
      tweets << Twitter.search(stream.hashtag, :rpp => 10)  
    end

    tweets.flatten.compact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  # GET /streams
  # GET /streams.json
  def index
    @streams = Stream.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @streams }
    end
  end

  # GET /streams/1
  # GET /streams/1.json
  def show
    @stream = Stream.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stream }
    end
  end

  # GET /streams/new
  # GET /streams/new.json
  def new
    @stream = Stream.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stream }
    end
  end

  # GET /streams/1/edit
  def edit
    @stream = Stream.find(params[:id])
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = Stream.new(params[:stream])

    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: 'Stream was successfully created.' }
        format.json { render json: @stream, status: :created, location: @stream }
      else
        format.html { render action: "new" }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /streams/1
  # PUT /streams/1.json
  def update
    @stream = Stream.find(params[:id])

    respond_to do |format|
      if @stream.update_attributes(params[:stream])
        format.html { redirect_to @stream, notice: 'Stream was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream = Stream.find(params[:id])
    @stream.destroy

    respond_to do |format|
      format.html { redirect_to streams_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.from_streams
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= AppConfig.title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/streams/_form.html.haml
= form_for @stream do |f|
  -if @stream.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stream.errors.count, "error")} prohibited this stream from being saved:"
      %ul
        - @stream.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :hashtag
    = f.text_field :hashtag
  .actions
    = f.submit 'Save'

app/views/streams/edit.html.haml
%h1 Editing stream

= render 'form'

= link_to 'Show', @stream
\|
= link_to 'Back', streams_path

app/views/streams/index.html.haml
%h1 Listing streams

%table
  %tr
    %th Hashtag
    %th
    %th
    %th

  - @streams.each do |stream|
    %tr
      %td= stream.hashtag
      %td= link_to 'Show', stream
      %td= link_to 'Edit', edit_stream_path(stream)
      %td= link_to 'Destroy', stream, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Stream', new_stream_path

app/views/streams/new.html.haml
%h1 New stream

= render 'form'

= link_to 'Back', streams_path

app/views/streams/show.html.haml
%p#notice= notice

%p
  %b Hashtag:
  = @stream.hashtag

= link_to 'Edit', edit_stream_path(@stream)
\|
= link_to 'Back', streams_path

app/views/tweets/_frame.html.haml
= stylesheet_link_tag "impress"
%h1#title= AppConfig.handle
%h2#streams= "Tweet: #{Stream.pluck(:hashtag)}"
%h2#author by @DavidBatey

app/views/tweets/_tweet.html.haml
.step.slide{data:{x: "#{Kernel.rand(8000)}", y:"#{Kernel.rand(6000)}", z:"#{Kernel.rand(30) + 80}"}}
  %p.tweeter= "@#{tweet.from_user}"
  %p.tweet= tweet.text

app/views/tweets/index.html.haml
= render 'frame'

#impress= render :partial => "tweets/tweet", :collection => @tweets

= javascript_include_tag "impress"